import { AppItem, CategoryItem, SiteSettings } from '../types';

export const INITIAL_CATEGORIES: CategoryItem[] = [
  { name: 'All Categories', slug: 'all', createdAt: Date.now() - 500000 },
  { name: 'Reward Apps', slug: 'reward-apps', createdAt: Date.now() - 400000 },
  { name: 'Gaming Apps', slug: 'gaming-apps', createdAt: Date.now() - 300000 },
  { name: 'Rummy & Cards', slug: 'rummy-cards', createdAt: Date.now() - 200000 },
  { name: 'Task & Survey', slug: 'task-survey', createdAt: Date.now() - 100000 },
];

export const INITIAL_SETTINGS: SiteSettings = {
  siteName: 'Yono Bonus Link',
  siteDescription: 'Explore verified official links, offers, and details for gaming, reward, and bonus applications.',
  logoUrl: '',
  telegramUrl: 'https://t.me/Job_wala_Akash',
  contactEmail: 'contact@yonobonuslink.com',
  heroHeading: 'Latest Bonus & Earning Apps',
  heroSubtitle: 'Explore the latest apps, offers and official links in one place.',
  responsibleGamingNotice: 'Please note: Some gaming or card applications may involve real-money elements or financial risk. Strictly 18+. Participate responsibly and verify legal availability in your state or region.',
};

export const INITIAL_APPS: AppItem[] = [
  {
    name: 'Yono VIP Rewards',
    slug: 'yono-vip-rewards',
    logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=240&auto=format&fit=crop&q=80',
    shortDescription: 'Official bonus portal for daily check-in rewards and loyalty incentives.',
    fullDescription: 'Yono VIP Rewards provides registered users with an official portal to view their activity tiers, daily spin passes, and promotional event rewards. All claims and offers are managed directly by the operator.',
    category: 'Reward Apps',
    appType: 'Reward App',
    bonusText: 'Daily Login Streak & Welcome Bonus Points',
    howItWorks: 'Sign up on the official platform, complete your profile verification, and claim your introductory bonus tier points through the daily tasks dashboard.',
    officialUrl: 'https://yono-games.example.com',
    telegramUrl: 'https://t.me/Job_wala_Akash',
    status: 'live',
    isNew: true,
    isFeatured: true,
    ageNotice: '18+ only. Terms and conditions apply.',
    legalNotice: 'Offer terms are subject to change without notice by the game publisher. Please verify all details on the official platform.',
    displayOrder: 1,
    createdAt: Date.now() - 86400000 * 2,
    updatedAt: Date.now() - 86400000 * 2,
  },
  {
    name: 'Rummy Gold Club',
    slug: 'rummy-gold-club',
    logoUrl: 'https://images.unsplash.com/photo-1511193311914-0346f16efe90?w=240&auto=format&fit=crop&q=80',
    shortDescription: 'Online multiplayer classic card game platform with sign-up chips.',
    fullDescription: 'Rummy Gold Club provides 13-card rummy and multiplayer tables. The app features practice modes, seasonal tournaments, and bonus chips for new accounts upon mobile OTP verification.',
    category: 'Rummy & Cards',
    appType: 'Rummy / Real-Money Gaming',
    bonusText: 'Sign-up Practice Chips & First Deposit Match (Operator T&C apply)',
    howItWorks: 'Download the client from the official website, register via OTP, and access beginner tables with complimentary practice credits.',
    officialUrl: 'https://rummygold.example.com',
    telegramUrl: 'https://t.me/Job_wala_Akash',
    status: 'live',
    isNew: true,
    isFeatured: true,
    ageNotice: '18+ only. Real money games involve financial risk. Please play responsibly.',
    legalNotice: 'Restricted in Andhra Pradesh, Assam, Nagaland, Odisha, Sikkim, and Telangana. Verify legality in your state before playing.',
    displayOrder: 2,
    createdAt: Date.now() - 86400000 * 4,
    updatedAt: Date.now() - 86400000 * 4,
  },
  {
    name: 'Daily Tasker Cash',
    slug: 'daily-tasker-cash',
    logoUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=240&auto=format&fit=crop&q=80',
    shortDescription: 'Earn gift cards and cashbacks by testing mobile apps and completing quick surveys.',
    fullDescription: 'Daily Tasker Cash allows members to earn redeemable reward points by answering community surveys, providing feedback on beta software, and watching sponsored interactive videos.',
    category: 'Task & Survey',
    appType: 'Earning App',
    bonusText: 'Instant 500 Welcome Coins on Profile Completion',
    howItWorks: 'Register with your verified email, pick from available research survey topics or app tests, and accumulate points directly redeemable into digital vouchers.',
    officialUrl: 'https://dailytasker.example.com',
    status: 'live',
    isNew: false,
    isFeatured: true,
    ageNotice: 'Open to users 16+. Valid payment identity required for redemption.',
    legalNotice: 'Payout thresholds and redemption options are determined solely by the third-party survey partners.',
    displayOrder: 3,
    createdAt: Date.now() - 86400000 * 7,
    updatedAt: Date.now() - 86400000 * 7,
  },
  {
    name: 'Teen Patti Royale',
    slug: 'teen-patti-royale',
    logoUrl: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=240&auto=format&fit=crop&q=80',
    shortDescription: 'Popular 3-card social card game with festive events and table bonuses.',
    fullDescription: 'Teen Patti Royale brings authentic 3-card poker style gameplay to your mobile device with smooth graphics, private room setups with friends, and weekly leaderboard rewards.',
    category: 'Rummy & Cards',
    appType: 'Rummy / Real-Money Gaming',
    bonusText: 'Daily Festive Spins & Referral Bonus Chips',
    howItWorks: 'Install the official application, join quick match lobbies or create a private room with table passcodes.',
    officialUrl: 'https://teenpatti-royale.example.com',
    status: 'live',
    isNew: true,
    isFeatured: false,
    ageNotice: 'Strictly 18+ only. Skill-based gaming with financial risk.',
    legalNotice: 'Users from restricted territories where card games with stakes are prohibited are strictly disallowed.',
    displayOrder: 4,
    createdAt: Date.now() - 86400000 * 1,
    updatedAt: Date.now() - 86400000 * 1,
  },
  {
    name: 'Spin & Win Arena',
    slug: 'spin-win-arena',
    logoUrl: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=240&auto=format&fit=crop&q=80',
    shortDescription: 'Casual arcade wheel spin game with shopping vouchers and daily coupons.',
    fullDescription: 'Spin & Win Arena is a casual entertainment portal where players participate in hourly token wheels to unlock discount coupons for partnered e-commerce stores.',
    category: 'Gaming Apps',
    appType: 'Gaming App',
    bonusText: '5 Free Daily Spins for Every Registered Player',
    howItWorks: 'Sign in every 4 hours to claim complimentary wheel spins and collect discount tokens in your wallet.',
    officialUrl: 'https://spinarena.example.com',
    status: 'live',
    isNew: false,
    isFeatured: false,
    ageNotice: 'All ages welcome. Coupon terms set by respective merchants.',
    legalNotice: 'Coupons have expiration dates. Check individual voucher details before redemption.',
    displayOrder: 5,
    createdAt: Date.now() - 86400000 * 12,
    updatedAt: Date.now() - 86400000 * 12,
  },
];
